"""Rendering, parsing, checking, and repairing the published ASS subtitles.

The subtitle model deliberately allows cues from *different* speakers to
overlap in time — people talk over each other — while any other overlap is a
pipeline or review defect. ASS is the output format because, unlike SRT, it
renders overlapping events and carries the speaker in each Dialogue's Name
field.
"""

from __future__ import annotations

import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

from .models import Cue, OutputMode


def _probe_default_file_mode() -> int:
    """Read the process umask once, at import, on the main thread.

    ``os.umask`` can only be read by setting it, so calling this concurrently
    would leave the process umask at 0 for whichever thread lost the race.
    """
    mask = os.umask(0)
    os.umask(mask)
    return 0o666 & ~mask


# ``tempfile.mkstemp`` deliberately creates private 0600 files and ``os.replace``
# keeps that mode, so an atomically written artifact would otherwise be
# unreadable by the media players, subtitle servers, and other users who need it.
DEFAULT_FILE_MODE = _probe_default_file_mode()


_LANGUAGE_COMPONENT_RE = re.compile(r"[^a-z0-9-]+")
_TIMESTAMP_RE = re.compile(r"^\s*(\d+):(\d{1,2}):(\d{1,2})[.,](\d{1,3})\s*$")
_SECTION_RE = re.compile(r"^\[(?P<name>[^\]]+)\]\s*$")
# ASS soft (\n) and hard (\N) line breaks both separate display lines here.
_LINE_BREAK_RE = re.compile(r"\\[nN]")

ASS_STYLE_NAME = "Default"

# The script resolution to author against when the input has no video to
# match: an audio-only download, or a probe that could not run. It is also the
# resolution the style is designed at, so every style metric scales from it.
DEFAULT_PLAY_RES = (1920, 1080)


def _metric(value: float, scale: float) -> str:
    """Format one fractional style metric, dropping a trailing ``.0``."""
    return f"{round(value * scale, 2):g}"


def ass_header(play_res: tuple[int, int] = DEFAULT_PLAY_RES) -> str:
    """Render the header for one script resolution.

    ``PlayRes`` must match the video: libass scales the script onto the frame
    per axis, so a script authored for 16:9 stretches every glyph when it is
    rendered over a vertical or 4:3 video. Because the whole header is
    generated from that one resolution, canonicalization can rewrite it
    wholesale, which makes header drift impossible rather than checkable.

    Every style metric is a fraction of the frame, so the subtitles keep the
    same size relative to the picture at any resolution. The type is scaled by
    whichever axis affords less, because a line that is sized off the height of
    a vertical video runs off both sides of it — libass does not break a CJK
    line — while each margin is a fraction of the axis it is taken out of.
    """
    width, height = play_res
    scale = min(width / DEFAULT_PLAY_RES[0], height / DEFAULT_PLAY_RES[1])
    margin_h = round(60 * width / DEFAULT_PLAY_RES[0])
    margin_v = round(40 * height / DEFAULT_PLAY_RES[1])
    return f"""[Script Info]
; Generated by YakiFlow
ScriptType: v4.00+
PlayResX: {width}
PlayResY: {height}
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: {ASS_STYLE_NAME},sans-serif,{max(1, round(64 * scale))},&H00FFFFFF,&H000000FF,&H00000000,&H7F000000,0,0,0,0,100,100,0,0,1,{_metric(3, scale)},{_metric(1.5, scale)},2,{margin_h},{margin_h},{margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


ASS_HEADER = ass_header()


def timestamp(seconds: float) -> str:
    """Render one ``H:MM:SS.cc`` ASS timestamp, quantized to centiseconds."""
    centiseconds = max(0, round(seconds * 100))
    hours, remainder = divmod(centiseconds, 360_000)
    minutes, remainder = divmod(remainder, 6_000)
    secs, centis = divmod(remainder, 100)
    return f"{hours:d}:{minutes:02d}:{secs:02d}.{centis:02d}"


def parse_timestamp(value: str) -> float | None:
    """Read one ASS timestamp into seconds, quantized to centiseconds."""
    match = _TIMESTAMP_RE.match(value)
    if match is None:
        return None
    hours, minutes, secs, fraction = match.groups()
    # Canonical ASS carries centiseconds; a single digit means tenths and a
    # millisecond fraction (an SRT habit) is quantized so the canonical
    # rewrite can repair it instead of rejecting the file.
    if len(fraction) == 1:
        centis = int(fraction) * 10
    elif len(fraction) == 3:
        centis = round(int(fraction) / 10)
    else:
        centis = int(fraction)
    return (
        int(hours) * 360_000 + int(minutes) * 6_000 + int(secs) * 100 + centis
    ) / 100


@dataclass(frozen=True, slots=True)
class AssEvent:
    """One parsed Dialogue event."""

    start: float
    end: float
    name: str
    text_lines: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class SubtitleProblem:
    """A structural defect found in a rendered subtitle file."""

    kind: str
    message: str


def sanitize_text_line(line: str) -> str:
    """Make one display line safe inside a Dialogue Text field.

    Braces delimit ASS override blocks — libass hides their content — so they
    are replaced with their fullwidth lookalikes instead of disappearing.
    """
    return line.replace("{", "｛").replace("}", "｝")


def sanitize_name(name: str) -> str:
    """Make a speaker label safe in the Name field.

    Every field before Text is comma-separated, so a comma or line break in
    the name would shift the remaining fields.
    """
    return name.replace(",", " ").replace("\n", " ").replace("\r", " ").strip()


def _event_text(text: str) -> tuple[str, ...]:
    lines = _LINE_BREAK_RE.split(text)
    return tuple(line.strip() for line in lines if line.strip())


def render_events(
    events: Iterable[AssEvent], play_res: tuple[int, int] = DEFAULT_PLAY_RES
) -> str:
    lines = [ass_header(play_res)]
    for event in events:
        text = r"\N".join(
            sanitize_text_line(line) for line in event.text_lines
        )
        lines.append(
            f"Dialogue: 0,{timestamp(event.start)},{timestamp(event.end)},"
            f"{ASS_STYLE_NAME},{sanitize_name(event.name)},0,0,0,,{text}\n"
        )
    return "".join(lines)


def cue_text_lines(cue: Cue, mode: OutputMode | str) -> tuple[str, ...]:
    mode = OutputMode(mode)
    translated = (cue.translated or "").strip()
    source = cue.source.strip()
    if mode is OutputMode.SOURCE:
        lines = [source]
    elif mode is OutputMode.TRANSLATED:
        lines = [translated or source]
    else:
        # Bilingual output deliberately puts the translation first.
        lines = [translated, source] if translated else [source]
    return tuple(
        part.strip()
        for line in lines
        for part in line.splitlines()
        if part.strip()
    )


def cue_event(cue: Cue, mode: OutputMode | str) -> AssEvent:
    return AssEvent(
        start=cue.start,
        end=cue.end,
        name=cue.speaker or "",
        text_lines=cue_text_lines(cue, mode),
    )


def render_ass(
    cues: Iterable[Cue],
    mode: OutputMode | str = OutputMode.BILINGUAL,
    play_res: tuple[int, int] = DEFAULT_PLAY_RES,
) -> str:
    return render_events((cue_event(cue, mode) for cue in cues), play_res)


def parse_ass(text: str) -> tuple[list[AssEvent], list[SubtitleProblem]]:
    """Parse Dialogue events, reporting the ones that do not parse.

    Only ``Dialogue:`` lines inside ``[Events]`` matter; the header is
    regenerated wholesale at publish time, so nothing in it is worth checking.
    """
    events: list[AssEvent] = []
    problems: list[SubtitleProblem] = []
    section = ""
    dialogue_count = 0
    for line in text.lstrip("﻿").replace("\r\n", "\n").split("\n"):
        header = _SECTION_RE.match(line.strip())
        if header is not None:
            section = header.group("name").strip().casefold()
            continue
        if section != "events":
            continue
        stripped = line.strip()
        if not stripped.lower().startswith("dialogue:"):
            continue
        dialogue_count += 1
        label = f"event {dialogue_count}"
        fields = stripped[len("dialogue:"):].split(",", 9)
        if len(fields) < 10:
            problems.append(SubtitleProblem(
                "unparsable", f"{label} has fewer than 10 Dialogue fields"
            ))
            continue
        start = parse_timestamp(fields[1])
        end = parse_timestamp(fields[2])
        if start is None or end is None:
            problems.append(SubtitleProblem(
                "unparsable", f"{label} has an invalid timestamp"
            ))
            continue
        text_lines = _event_text(fields[9])
        if not text_lines:
            problems.append(SubtitleProblem(
                "empty_text", f"{label} has no subtitle text"
            ))
            continue
        events.append(AssEvent(start, end, fields[4].strip(), text_lines))
    return events, problems


def _event_label(event: AssEvent) -> str:
    label = f"event at {timestamp(event.start)}"
    return f"{label} ({event.name})" if event.name else label


def event_problems(events: Sequence[AssEvent]) -> list[SubtitleProblem]:
    """Report ordering and overlap defects among parsed events.

    Overlap between two different named speakers is legitimate crosstalk.
    Everything else — same speaker, either side unnamed — cannot be two people
    talking at once and is therefore a defect. Because legal overlaps exist,
    an event may overlap one that is several positions back, so each rule
    tracks its own running maximum instead of comparing neighbours.
    """
    problems: list[SubtitleProblem] = []
    named_max_end: dict[str, float] = {}
    unnamed_max_end = float("-inf")
    global_max_end = float("-inf")
    previous_start = float("-inf")
    for event in events:
        label = _event_label(event)
        if event.end < event.start:
            problems.append(SubtitleProblem(
                "end_before_start", f"{label} ends before it starts"
            ))
        if event.start < previous_start:
            problems.append(SubtitleProblem(
                "out_of_order", f"{label} starts before the event above it"
            ))
        previous_start = max(previous_start, event.start)
        if event.name:
            overlapping = (
                event.start < named_max_end.get(event.name, float("-inf"))
                or event.start < unnamed_max_end
            )
            if overlapping:
                problems.append(SubtitleProblem(
                    "overlap",
                    f"{label} overlaps an earlier cue of the same or an "
                    "unnamed speaker",
                ))
            named_max_end[event.name] = max(
                named_max_end.get(event.name, float("-inf")), event.end
            )
        else:
            if event.start < global_max_end:
                problems.append(SubtitleProblem(
                    "overlap", f"{label} has no speaker and overlaps an earlier cue"
                ))
            unnamed_max_end = max(unnamed_max_end, event.end)
        global_max_end = max(global_max_end, event.end)
    return problems


def ass_problems(text: str) -> list[SubtitleProblem]:
    """Report every structural defect in one rendered subtitle file."""
    events, problems = parse_ass(text)
    return problems + event_problems(events)


def alignment_problems(
    artifacts: Sequence[tuple[str, Sequence[AssEvent]]],
) -> list[SubtitleProblem]:
    """Report cue drift between subtitle files that must stay equivalent."""
    if len(artifacts) < 2:
        return []
    problems: list[SubtitleProblem] = []
    reference_name, reference = artifacts[0]
    for name, events in artifacts[1:]:
        if len(events) != len(reference):
            problems.append(SubtitleProblem(
                "artifact_mismatch",
                f"{name} has {len(events)} cues but {reference_name} has "
                f"{len(reference)}",
            ))
            continue
        for index, (expected, event) in enumerate(zip(reference, events), 1):
            # Both sides are centisecond-quantized by parse, so exact
            # comparison is exact equality of intent.
            if (
                expected.start != event.start
                or expected.end != event.end
                or expected.name != event.name
            ):
                problems.append(SubtitleProblem(
                    "artifact_mismatch",
                    f"{name} cue {index} does not share the timing and "
                    f"speaker of {reference_name}",
                ))
                break
    return problems


def _event_sort_key(event: AssEvent) -> tuple[float, float, str]:
    return (event.start, event.end, event.name)


def canonicalized_ass(
    text: str, play_res: tuple[int, int] = DEFAULT_PLAY_RES
) -> str | None:
    """Return ``text`` rewritten into canonical form, or ``None``.

    ``None`` means either "already canonical" or "not mechanically fixable" —
    the caller re-checks with :func:`ass_problems` either way. Rewriting
    replaces the whole header, re-sorts the events by ``(start, end, name)``,
    and normalizes timestamps, field layout, and brace sanitization. ``play_res``
    must be the resolution the file was published at, or the rewrite would
    "repair" a reviewed file into a header that no longer matches its video.
    """
    events, problems = parse_ass(text)
    if problems or not events:
        return None
    canonical = render_events(sorted(events, key=_event_sort_key), play_res)
    return None if canonical == text else canonical


def write_text_atomic(path: Path, text: str) -> None:
    """Replace ``path`` only once the new content is durably on disk.

    Every subtitle artifact is the sole copy of work that cannot be regenerated
    — a reviewed file most of all — so no writer may truncate one in place.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        os.chmod(temp_name, DEFAULT_FILE_MODE)
        os.replace(temp_name, path)
    finally:
        if os.path.exists(temp_name):
            os.unlink(temp_name)


def write_ass_atomic(
    path: Path,
    cues: Iterable[Cue],
    mode: OutputMode | str,
    play_res: tuple[int, int] = DEFAULT_PLAY_RES,
) -> None:
    write_text_atomic(path, render_ass(cues, mode, play_res))


def _language_component(language: str) -> str:
    component = language.strip().lower().replace("_", "-")
    component = _LANGUAGE_COMPONENT_RE.sub("-", component).strip("-")
    if not component:
        raise ValueError("subtitle language cannot be empty")
    return component


def output_modes(mode: OutputMode | str) -> list[OutputMode]:
    """Expand one configured output mode into the modes actually written."""
    mode = OutputMode(mode)
    return (
        [OutputMode.SOURCE, OutputMode.TRANSLATED, OutputMode.BILINGUAL]
        if mode is OutputMode.ALL
        else [mode]
    )


def publish_outputs(
    base: Path,
    cues: Iterable[Cue],
    mode: OutputMode | str,
    *,
    source_language: str | None = None,
    target_language: str | None = None,
    play_res: tuple[int, int] = DEFAULT_PLAY_RES,
) -> list[Path]:
    cues = list(cues)
    modes = output_modes(mode)
    suffixes = {
        OutputMode.SOURCE: ".source.ass",
        OutputMode.TRANSLATED: ".translated.ass",
    }
    if OutputMode.BILINGUAL in modes:
        if source_language is None or target_language is None:
            raise ValueError("bilingual output requires source and target languages")
        suffixes[OutputMode.BILINGUAL] = (
            f".{_language_component(source_language)}-"
            f"{_language_component(target_language)}.ass"
        )
    paths = []
    for selected in modes:
        path = base.parent / f"{base.name}{suffixes[selected]}"
        write_ass_atomic(path, cues, selected, play_res)
        paths.append(path)
    return paths
